language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
      script
    - npm run test -- --reporter=lcov
notifications:
  email: false
after_success:
  ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
